export const messageTypesOptions = [
  { label: "POST_ATTRIBUTES_REQUEST", value: "POST_ATTRIBUTES_REQUEST" },
  { label: "POST_TELEMETRY_REQUEST", value: "POST_TELEMETRY_REQUEST" },
  { label: "TO_SERVER_RPC_REQUEST", value: "TO_SERVER_RPC_REQUEST" },
  {
    label: "RPC_CALL_FROM_SERVER_TO_DEVICE",
    value: "RPC_CALL_FROM_SERVER_TO_DEVICE",
  },
  { label: "RPC_QUEUED", value: "RPC_QUEUED" },
  { label: "RPC_SENT", value: "RPC_SENT" },
  { label: "RPC_DELIVERED", value: "RPC_DELIVERED" },
  { label: "RPC_SUCCESSFUL", value: "RPC_SUCCESSFUL" },
  { label: "RPC_TIMEOUT", value: "RPC_TIMEOUT" },
  { label: "RPC_EXPIRED", value: "RPC_EXPIRED" },
  { label: "RPC_FAILED", value: "RPC_FAILED" },
  { label: "RPC_DELETED", value: "RPC_DELETED" },
  { label: "ACTIVITY_EVENT", value: "ACTIVITY_EVENT" },
  { label: "INACTIVITY_EVENT", value: "INACTIVITY_EVENT" },
  { label: "CONNECT_EVENT", value: "CONNECT_EVENT" },
  { label: "DISCONNECT_EVENT", value: "DISCONNECT_EVENT" },
  { label: "ENTITY_CREATED", value: "ENTITY_CREATED" },
  { label: "ENTITY_UPDATED", value: "ENTITY_UPDATED" },
  { label: "ENTITY_DELETED", value: "ENTITY_DELETED" },
  { label: "ENTITY_ASSIGNED", value: "ENTITY_ASSIGNED" },
  { label: "ENTITY_UNASSIGNED", value: "ENTITY_UNASSIGNED" },
  { label: "ATTRIBUTES_UPDATED", value: "ATTRIBUTES_UPDATED" },
  { label: "ATTRIBUTES_DELETED", value: "ATTRIBUTES_DELETED" },
  { label: "ALARM_ACKNOWLEDGED", value: "ALARM_ACKNOWLEDGED" },
  { label: "ALARM_CLEARED", value: "ALARM_CLEARED" },
  { label: "ALARM_ASSIGNED", value: "ALARM_ASSIGNED" },
  { label: "ALARM_UNASSIGNED", value: "ALARM_UNASSIGNED" },
  { label: "COMMENT_CREATED", value: "COMMENT_CREATED" },
  { label: "COMMENT_UPDATED", value: "COMMENT_UPDATED" },
  {
    label: "ENTITY_ASSIGNED_FROM_TENANT",
    value: "ENTITY_ASSIGNED_FROM_TENANT",
  },
  { label: "ENTITY_ASSIGNED_TO_TENANT", value: "ENTITY_ASSIGNED_TO_TENANT" },
  { label: "TIMESERIES_UPDATED", value: "TIMESERIES_UPDATED" },
  { label: "TIMESERIES_DELETED", value: "TIMESERIES_DELETED" },
];
